In [ ]:
#coding=utf-8
#Email of the author: zjduan@pku.edu.cn
'''
0.id: ad identifier
1.click: 0/1 for non-click/click
2.hour: format is YYMMDDHH, so 14091123 means 23:00 on Sept. 11, 2014 UTC.
3.C1 -- anonymized categorical variable
4.banner_pos
5.site_id
6.site_domain
7.site_category
8.app_id
9.app_domain
10.app_category
11.device_id
12.device_ip
13.device_model
14.device_type
15.device_conn_type
16.C14
17.C15
18.C16
19.C17
20.C18
21.C19
22.C20
23.C21
'''
import pandas as pd
import math


In [ ]:
df =  pd.read_table("./train_i.txt")
print(df)

In [ ]:
df2 =  pd.read_table("./train_x.txt")
print(df2)

In [ ]:
df3 =  pd.read_table("./train_y.txt")
print(df3)

In [ ]:
import numpy as np
value = np.array(df2)
print(value)


In [8]:
index = np.array(df)
print(index)

[['0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22']
 ['0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22']
 ['0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22']
 ...
 ['0 1541666 24 46 632 462 42 25 26 27 28 11335 207 29 35 539 30 31 327 32 328 40 159']
 ['0 1541666 24 34 51 47 48 493 57 58 321037 1542031 641 29 35 261 30 31 181 49 44 640 63']
 ['0 1541666 24 34 36 37 38 25 26 27 28 190733 107 29 35 555671 30 31 415544 32 188 43 84218']]


In [ ]:
print(index.shape[0])

ValueError: invalid literal for int() with base 10: '0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22'

In [9]:
idd = np.loadtxt('./train_i.txt',dtype=np.int32)
print(idd)

[[      0       1       2 ...      20      21      22]
 [      0       1       2 ...      20      21      22]
 [      0       1       2 ...      20      21      22]
 ...
 [      0 1541666      24 ...     328      40     159]
 [      0 1541666      24 ...      44     640      63]
 [      0 1541666      24 ...     188      43   84218]]


In [10]:
idd = np.array(idd)

In [11]:
print(idd.max())

1544488


In [12]:
value = np.loadtxt('./train_x.txt',dtype=np.int32)
label = np.loadtxt('./train_y.txt',dtype=np.int32)

In [13]:
value = np.array(value)
label = np.array(label)

In [14]:
from collections import  Counter
print(Counter(idd.flatten()))


IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [15]:
a = Counter(idd.flatten())

In [16]:
b =dict(a)

KeyError: '0'

In [17]:
import operator
sorted_list= sorted(b.items(), key=operator.itemgetter(1))[::-1]

In [18]:
print(sorted_list[1][1])

38136550


In [19]:
train_id_mapping = {sorted_list[i][0]:i for i in range(len(sorted_list))}

In [20]:
for i in train_id_mapping.keys():
    print(i)

0
31
30
29
24
35
28
34
26
27
25
40
32
48
47
51
11
49
42
33
46
58
63
44
38
66
37
36
57
84218
10
41
39
62
59
98
56
367
61
86
43
108
83
82
117
115
182
72
408
45
113
93
68
109
101
368
177
27272
119
829
99
118
131
254
73
67
209
121
199
139
76
95
94
2154
70
268
559
100
106
105
97
96
135
111
122
110
103
127
84217
8018
280033
393
250939
104
126
84
284
1261
176
175
1234
149
148
380
129
180
2834
120
215
128
415544
240
818315
453
16890
1130976
141
140
1945
642
171
160
114403
147
144
8014
472227
472226
239
262862
216
247
8135
114
8134
5335
290
146
1116
52
78
60
69
124
71
79
65
145
6155
81
1084409
138
5649
50
865
1119883
116
8532
6444
362
283405
263832
107
250940
246
280001
1140342
188
134
1996
75
308539
454
1394811
1394810
1394809
1394808
202
194
439
170
1156989
295438
210
200
250943
927
464
250942
463
985333
5660
545831
178
214
1036
196
1109645
1727
137
136
1399690
142
133
477
476
314
276
364
363
925614
925613
1776
8013
8012
102
1096034
198
595131
2364
128279
322035
250938
457
242
241
319
231632


374
2303
27354
2652
940
1253844
11627
1885
11626
1471
1470
509
8154
97124
730
2446
3670
3669
914
2125
1306
1128
1577
1502
3042
774
1782
1781
792
1676
27199
1715
7660
925663
925662
813
1582
5947
899
614152
1835
2902
1317206
410
1275
1274
2492
3114
2688
1140
1071
985291
13265
1070
10003
264
408608
429
5093
535
2335
995
1000
2264
5684
2205
1784
4742
447
887
533
1546
361
360
36597
408607
14280
1094
2105
998
855
1074
1292
3044
4
2143
2137
2136
2603
577
441333
441349
441312
3137
3136
4592
382250
2192
1344
441354
4882
601
441542
1175
402706
441313
447504
5343
1044002
441420
1962
1339
2029
835
831
830
482
901
540
40074
219077
2532
614214
1367
909865
2541
5240
1111
442
477463
10442
6596
2894
4762
10432
8520
8315
1880
2895
168
1658
129291
2893
2447
1706
2224
4178
1157025
1436
19238
16386
2576
403697
403159
1304441
1304440
1237
532
12288
7151
403829
1861
3391
2314
6314
1687
12520
2553
1365
403693
1656
652528
5277
1259
834
1762
8632
749392
477736
4163
403155
1271
508
7124
2259
36580
28944
1069
210

2412
664676
6365
172154
15635
2631
3231
932080
3528
3887
1105774
415673
9827
886
885
6136
7028
930438
2250
18640
10970
27932
8180
6334
10311
545342
1109360
216351
38627
250966
164053
164052
1304392
171026
14441
823106
10292
5492
986001
842
841
13042
2056
10338
3859
3485
989584
5906
22992
19728
986438
10905
27231
23526
20710
20709
2035
6285
644
1134071
415643
1837
1836
17067
2797
4563
10354
3296
892
891
14246
1104316
20571
10990
10989
3011
163285
163284
28141
4079
415676
94355
171673
39599
11073
5136
1102628
7936
11711
987104
5847
1202256
12917
1011
1010
9850
7341
1013
1012
17284
57103
2563
3540
8454
41651
5298
231518
2309
415677
9099
483781
12872
2824
9865
4200
692741
415664
15728
1497
1496
20507
30239
3098
1907
11400
5887
62247
7893
4013
115643
2566
990437
527
526
12959
7829
2328
14007
4456
9375
1699
490605
8050
5333
8049
1860
8269
6574
1541
1540
4016
97617
2225
8476
989283
85141
9298
993909
12198
4246
7712
37230
226271
2934
75084
75083
37205
10045
517773
415802
237583
11325
4134
8665

27153
18349
4470
3483
729
728
36760
1283650
968533
28370
28369
13918
30874
16009
8073
59370
27470
9372
8772
8749
6353
4265
15536
11507
210555
140385
19120
75587
11971
27198
14304
3590
3194
28757
21312
16912
16677
5884
1634
1426
72274
30534
27945
19300
19192
9429
8439
6536
6402
3014
2750
34565
33009
15781
14300
7585
3926
12378
8086
6991
3575
195959
27260
27169
27168
16730
9136
3347
3207
2787
1297878
138688
56046
44601
18781
14709
14087
3139
1044019
968432
17693
8110
1474360
210663
36721
36170
12235
4989
17200
430933
27523
15624
8062
6547
6224
64534
12749
12598
993597
993596
323369
52057
16156
1068655
14005
10201
911661
27791
21947
16159
15689
7923
3786
1457923
1321036
494723
15630
9206
33104
27364
13261
6787
5113
4663
36588
10991
10753
10077
7220
1779
456377
54242
27873
17295
16524
15201
8398
6635
22483
17602
14926
13979
13739
9660
7070
4994
3148
3147
17733
12888
3781
15810
6089
4922
2948
1283393
28604
27436
22357
21207
3500
28815
1069077
44286
20184
17066
9992
5163
2170
29556
23993
224

29678
29035
8760
6728
4939
1986
1394902
280731
39373
37743
22652
12746
8091
2868
1431979
74919
70526
50884
33930
16416
15724
13351
6929
3919
50947
39180
17232
14871
7706
5096
2032
52339
34884
34112
12547
8214
6564
858171
94960
63495
51314
46100
29126
28671
28098
18111
5313
2323
518042
251976
140505
72515
17863
13022
9225
3693
1037479
693227
88966
67969
57222
45355
37032
32926
30722
29704
19719
16703
13869
11086
8804
7562
175910
136961
43663
28993
23154
17866
8268
1056
877
1219159
78880
63836
49781
29987
23395
18795
15083
8691
2283
1075615
521755
484154
84215
84214
40824
31956
20114
18263
17313
8679
7966
7196
6570
1240175
1240174
338269
84706
52329
38664
28234
16899
9790
9410
9409
1399764
770118
458392
87792
45689
36592
29709
22324
12593
10463
9513
7438
5865
1432384
194373
27210
18867
15245
11357
10924
9451
8240
990799
274106
231672
115644
50557
37676
37381
35882
33827
29199
25892
24652
18597
18097
17677
17014
14934
12356
8153
81190
63995
52901
27742
20480
16878
11803
136855
38209
31211

74944
55527
54768
37321
35711
32598
31892
29384
18453
18388
12824
8433
2931
137476
122530
69933
68183
58635
52139
49458
48985
40420
38070
31157
28886
28035
27775
27217
23932
15364
13805
12692
12147
10636
1434379
1434154
243565
159059
98642
98641
85019
65008
62767
53765
51826
47288
46608
39989
39931
38181
31080
28468
27258
25640
16806
16658
15818
14967
14836
10898
7863
4231
3541
1227684
785771
296136
286936
251631
170958
117567
94230
89688
80813
63906
55639
50188
48931
37934
37400
21465
21464
19296
9231
3816
978919
893468
251102
251080
242619
139660
132130
89243
84415
76607
76143
67541
63286
62375
56643
55288
50723
49978
49159
35790
29180
27821
23909
21610
18208
17226
15485
13633
10686
10505
791248
580991
331725
266527
251645
172027
91652
79827
75689
72564
63818
54957
39973
37232
32169
31232
30901
30760
29656
26791
19016
15910
12286
10322
8114
7079
1433102
1089718
347184
262657
173154
171385
97139
89409
80494
79964
68508
58266
53741
45043
44869
42782
38482
34181
26427
21335
19640
15795


92379
91188
87906
78892
77222
73274
63218
52835
51136
50696
44142
41054
40915
38299
31089
30079
27977
26454
21980
16724
9495
9022
8660
8543
6881
6527
5674
1275362
500672
494968
386801
377615
293930
289216
244132
178864
134161
132576
118226
108793
106598
95361
93207
90639
84453
66005
65581
64133
48580
39561
38492
38360
36087
32721
30720
28951
27874
27420
22494
22214
20390
19170
18223
17076
14952
13982
13970
13629
12975
10573
8915
6743
4919
4631
1433940
1192349
1119914
650969
470587
322094
266693
196883
181957
174688
174669
169616
163395
156105
127038
66553
64213
59005
52822
52416
48228
45505
40756
35349
34386
30310
18533
18506
16875
15537
12822
9740
9634
9102
5846
5580
3916
2918
1395258
1329375
1225769
927938
779061
772362
585329
560335
483119
308649
295820
281462
220457
173008
172795
138806
132720
128806
112895
112629
105982
87707
85369
82661
70863
67586
63894
51517
45904
38742
37620
36819
35931
33368
27409
23732
21366
17260
13998
13048
12572
11687
8897
7754
6644
1486299
1174007
105974

353138
310220
270567
264377
179646
176473
173259
160556
136781
133320
127219
111087
109306
104901
92011
90503
88046
81107
76749
76748
62989
55024
50794
43660
23615
22457
18165
15673
15651
15136
8800
5871
5073
1399974
1399751
612160
541512
420996
353909
313171
265993
251965
224541
182578
177040
174546
113997
86941
75691
72943
70425
65462
61247
54228
45042
25510
23939
15826
15627
13928
9667
8844
5866
4624
1118733
559716
527949
443070
394094
387727
346988
280428
251874
191385
183070
180335
173725
155468
138260
121924
117172
114916
92606
89427
88261
85150
83824
81677
69469
67029
61965
55357
52085
47436
46068
38301
37444
35628
34313
30411
30366
30341
29618
28724
26985
25799
22582
20255
19733
17478
16526
9568
7414
5640
5224
3904
1400079
1396199
1211438
1085118
1060341
766947
251430
200091
175618
170126
165110
164735
154525
148235
110947
105679
96428
94574
89787
80634
78980
76332
66220
64578
63618
53687
51743
51338
48335
45649
39853
39363
38728
36330
32510
31742
28517
24894
23898
21449
19445


52264
51341
49485
48081
42296
38293
33769
31483
20340
19586
16177
12567
11686
10950
9678
6093
1395032
1122263
622955
563432
488163
361676
354105
350456
281137
246163
235351
224052
223819
211059
196175
189521
180155
178643
167693
109909
105774
94034
83099
82991
81553
78275
78100
76921
76126
75580
64721
63807
60592
58905
52910
51575
51486
51118
50980
50561
49289
44114
36554
32549
31809
30629
27823
24744
21861
21564
20907
19634
18907
18234
17110
15430
14403
5222
5099
4154
1520867
1483825
1269181
1242166
1120121
1112338
524590
466373
359182
308768
304824
267375
253353
251694
251334
201437
182414
172671
172262
135430
129560
119084
109818
96835
93967
88876
77300
74039
65404
61172
57451
53385
52457
50719
48669
43745
40604
39459
37479
36856
34460
30578
28399
28276
27293
27216
24058
22686
22372
20624
20529
20422
19893
18479
15762
15390
12189
12119
10938
10901
9627
6520
6503
4264
1404025
1400333
1192272
559739
397557
346011
334113
234072
209493
190960
190630
177898
176087
130892
128316
99415
987

138069
133414
129644
106526
96763
96552
95807
94093
88198
84940
80778
80524
68473
66931
61676
58662
57273
54770
48159
48024
46549
41831
32416
29330
29308
29056
29049
28583
26322
25235
20891
20499
17044
14665
13653
10181
8580
7420
5595
3974
2710
1805
1342908
1333697
1192537
1171792
1120049
1119970
912756
792346
663444
659078
463980
394641
309489
296599
254695
154539
146311
134599
128604
128384
96427
91688
88906
81296
78948
73878
71576
71035
66938
64337
63249
61018
60943
57080
54607
48025
44314
44095
42026
41018
39406
38980
38238
37453
37430
36099
34397
31049
29562
29125
28843
28801
28635
28611
28426
18793
17426
16772
14931
14248
13836
11030
8593
6463
3991
1324841
1100194
988571
897621
657615
635819
565806
554502
400890
376227
309208
296242
281315
252358
251875
243411
211767
211602
197789
150724
126790
117651
115553
114931
114433
113998
108032
92089
87932
84252
75729
71001
70870
70822
63344
62617
61975
61746
60646
57632
52702
48894
47226
47164
46814
46219
45643
44511
44333
43284
39995
39

170959
158480
145149
144538
142648
138254
128082
115089
113364
105238
100831
99780
97720
96312
96236
95594
94380
93647
92256
92212
90016
87156
85703
85039
80360
78909
77107
71933
70196
65022
64198
63969
63768
63453
63452
54216
52704
52068
51244
50668
49607
48438
43401
41879
41871
41715
40938
38481
38474
38035
36173
36147
35706
33634
33168
32065
29967
29120
28684
23797
19419
18613
17798
16339
15960
15287
14157
13184
12302
11800
10747
9280
7633
6998
4532
3244
2489
2430
1475939
1400359
1395336
1263364
1169799
992684
963025
926082
697822
582353
560847
560040
559896
526130
483076
481378
441446
430197
356052
345368
320254
309010
297114
296902
280315
264769
251395
241538
213402
170843
165601
160064
159091
158982
152944
150506
138352
122162
121650
119011
111480
108108
103483
98347
97827
94935
93479
88995
84531
84187
81237
78260
76930
74797
72712
71802
70222
67481
67480
65786
65316
64375
53536
53115
47787
47627
47123
47002
44247
43048
42808
40878
40842
40570
40048
38881
38737
38387
32960
30646


51835
48137
47266
45804
44865
43003
40252
37937
37488
36992
36658
36464
36294
35769
35508
35501
33800
32808
32804
30774
28002
27815
27598
27336
26349
25006
24728
24698
22434
21935
21813
19428
19143
18659
18480
18219
16837
12360
9106
8789
8788
7974
1313099
1282049
1253274
1244630
1244629
1157088
1140528
1120758
997593
988817
873970
565080
559990
537850
532187
529451
484671
484504
483525
465747
443078
429016
413174
395287
385365
327479
315007
311627
305142
296161
295696
280416
276246
271129
264414
251766
209617
205512
197572
179939
179202
178038
160976
147838
144890
140855
135758
134394
132333
128269
123826
116010
114940
109255
107901
106866
106666
102355
97765
97231
97161
95787
95555
94845
94046
93607
92477
89810
89469
87010
86868
86348
85890
83657
83572
82816
80532
79214
78885
78034
75258
74994
74959
74931
69495
67926
67595
66520
65283
64286
64060
60857
57305
53611
51225
50565
50447
49343
48138
46711
46373
43323
42421
41580
41513
40526
39914
39807
39330
38817
37965
36656
34417
33053
32

86264
85627
84323
83430
83349
83293
82737
82651
81721
81033
80319
79303
79232
78460
76743
76180
74926
72240
70949
69404
69116
65705
65038
63312
62390
58229
56564
56554
55529
53606
51121
51033
49567
49363
46770
46647
42933
42698
41951
39632
37454
36779
35195
34216
33792
33544
32888
32490
32059
31284
29833
29779
29421
28636
28032
27189
25683
25606
24127
23817
23386
22675
21674
19916
18242
17563
16866
16648
14498
13713
6805
3802
3141
2524
1468057
1421921
1394953
1352432
1249361
1225223
1225222
1130969
1127906
1123090
1122242
1120957
1120009
1119893
1099412
1083251
1057323
968500
887746
781133
781132
659058
631052
587157
578407
560369
559815
538377
534170
531513
521150
506421
494973
492897
489286
487410
484426
483018
477804
470498
464906
440445
416277
415922
415844
402232
392450
385591
385006
384415
378244
378079
365898
349115
347646
342909
330228
325431
322118
297090
296683
296215
275924
268006
264468
252994
248101
210021
204971
194170
181610
177896
166855
166854
163805
158678
158604
1543

261810
256865
255564
252539
251349
242346
236860
234732
224925
219941
218749
217639
212910
210809
209877
207517
201829
201611
196225
190427
178502
176802
176175
174090
170718
168738
166226
165168
160260
158456
157949
153793
152560
151256
149256
145283
137216
130725
130190
129208
128503
125835
125533
125532
122642
118638
117739
117581
115401
113296
111696
109878
109877
106211
105103
104521
101778
101753
98879
95539
94844
94802
93968
91075
90762
89812
87949
86563
85210
82497
80465
76639
76167
75853
75469
75464
74676
69748
69686
68575
65711
65512
64652
63400
62620
61144
59820
59430
59375
58863
57301
57000
56132
55557
54193
53427
48837
48616
48433
46375
45611
42514
38297
38196
38061
37718
36048
35773
35033
34353
34241
33885
33839
33697
29714
29481
28849
27962
27611
27360
27098
26156
25119
24612
23464
22085
21549
21428
20760
20439
20430
19901
19138
18872
17170
16883
16834
16149
15068
14807
14500
12724
12481
9292
8287
5647
4590
1966
1460254
1416517
1399975
1325245
1325244
1223884
1211508
114

87380
87370
87254
86481
86175
85833
85508
85444
82421
82285
80208
79975
78537
78348
76880
76098
74838
74837
74815
72520
71027
70059
69770
68448
68425
67366
67355
67273
66872
65428
64414
62976
62317
61993
61915
61886
61491
58315
55548
54328
53263
51337
51069
50814
49532
49476
47920
47844
45551
45141
44275
42556
41070
39784
39294
39247
35493
34399
33512
32550
32237
29617
29162
28279
27363
24207
19671
17423
16728
15800
14869
11105
10840
9622
7328
6069
4502
2357
1456205
1400738
1400399
1400316
1399985
1399913
1395276
1359263
1349528
1330063
1317411
1283406
1254632
1253188
1250597
1248039
1171235
1141700
1141040
1140869
1121445
1121190
1120983
1098135
995231
994802
993108
964290
907384
806375
804586
710286
660344
566133
538514
536625
535694
532433
531119
529135
528442
521925
494794
489675
484315
479056
463587
463072
449623
447607
442455
435465
417550
417225
416746
405877
399463
389456
377526
371940
351315
333922
314731
265138
264291
253037
252474
252020
251749
251381
251301
245375
244370
24

159684
158970
157847
157652
157038
156527
156510
154368
151395
146149
144879
143768
143747
140810
140381
138432
135058
128649
128541
128247
128088
124825
124749
122793
122784
121600
120498
119939
119191
118022
117778
117705
115861
115806
115136
115012
114686
114680
113597
112632
111813
111015
107582
106404
106157
106134
102247
102039
98639
97780
97518
97517
94693
91321
90665
90222
89863
88580
87132
86142
85345
85193
84594
84572
83266
79631
78180
77027
76311
75876
74991
74849
74696
74303
71995
71962
71700
70914
68782
67815
67264
66256
64831
64541
63590
63509
62677
62254
60653
59576
55946
55582
54858
52366
51515
51035
50797
50516
49919
40993
40253
38886
38835
35439
34763
34364
33550
33527
32078
31999
31607
31250
30453
29255
25070
23126
19479
17966
17608
15991
12889
12409
10545
8228
8096
7545
7540
5254
1578
1534403
1531477
1499648
1478927
1418096
1400297
1400162
1395042
1275996
1263825
1263824
1192193
1175226
1141150
1130710
1125811
1120998
1120744
1108381
1083749
1017700
993638
909531
88

96728
95829
95028
94057
94050
93654
93133
92765
92246
90191
88600
87043
85619
83846
82582
82385
80705
79862
78804
77711
75995
75750
75570
74965
74904
74828
74613
74351
71883
70851
70673
70417
70408
69558
69383
67773
67664
66968
66013
64964
64342
63757
63422
63370
63236
61351
59018
58493
57425
51859
51621
51597
51060
47155
46348
45518
44212
44036
43870
41724
41183
40589
40216
39513
39395
39252
37845
37535
37252
36984
35607
34403
33616
30811
30582
30359
29467
29164
27029
26483
22009
21856
19807
18808
18273
18107
17333
16857
16212
16088
15874
15586
14434
14025
11891
9768
8929
5869
5166
3572
1551
1516151
1495162
1441773
1415385
1400273
1398290
1362349
1340108
1340107
1275825
1253378
1253311
1253110
1197396
1194280
1171414
1157413
1140902
1132900
1130977
1121668
1120488
1120111
1075381
1059843
1014011
991841
988896
988789
987079
973024
913153
879551
843451
841785
797665
783546
758791
693678
657613
650656
618933
609058
600772
592954
590003
580078
578021
567054
557574
539985
534200
532844
529

70109
70011
69189
68964
66519
66449
65547
65049
64963
64945
64051
63345
61639
61214
60937
59150
58812
58261
58061
57788
55667
54693
54366
52979
51591
50599
50099
49022
48863
47946
47901
45794
43352
42801
42401
40139
39086
38658
38392
38369
37801
37023
36799
33870
32362
30623
29144
28675
27377
27247
26473
25555
25528
24979
24103
23788
23708
21876
21327
21259
19868
19447
17445
16077
15719
15682
15678
13864
12277
10844
9692
8795
7205
6667
5023
2711
1483661
1400843
1400582
1400579
1400576
1400432
1400137
1395141
1369068
1347182
1326473
1312511
1279659
1277122
1276762
1276597
1257943
1253155
1248664
1236785
1186191
1140954
1124044
1120762
1107674
1105024
1087895
1087516
1064419
1064418
1055033
1035277
1035276
1028560
1005947
999253
997956
991942
986376
981018
927761
920636
904750
850676
826215
818645
782430
763688
760421
740491
712995
707872
693874
672214
670833
650018
637045
628300
613562
588883
582044
581127
577590
576234
570316
552603
551454
544793
536116
527552
523752
505202
494999
4949

1120308
1101572
1100344
1089705
1087864
1085423
1062952
1055068
1039993
1031405
1029857
1020864
1002105
1001658
995037
949835
910602
904138
883007
809155
801898
799708
781101
781100
760191
759360
750939
745383
700183
699982
669332
657526
654264
650752
641671
616440
592737
588333
587852
575655
567189
561766
547828
534156
531341
530710
527248
521605
497530
489623
485964
483016
480703
460432
451635
450826
445945
445944
436249
427888
415981
409547
397410
393319
392039
389917
384346
383108
382100
375472
374116
372905
369221
363743
350478
347524
315446
313820
313819
312672
311798
303049
299735
298125
296134
295198
295197
291061
286612
286163
282335
282115
282035
281271
280748
278039
275258
274775
271494
264530
261333
259124
256690
256182
255501
252763
252115
252007
251666
251385
251300
248784
247126
243715
242655
240606
239850
233525
232467
231668
230198
226906
223318
222785
221490
220839
220006
219186
218207
215549
212563
208167
208166
207844
206471
203661
202981
202508
202347
200072
198595

264700
264495
264193
262865
262308
261172
258381
256859
255837
254239
253808
251451
251371
251220
251070
250431
249043
247464
247289
247163
247105
246686
245098
243690
243337
243303
242012
241496
241457
235275
233024
232974
232018
231553
231466
223478
223340
219734
218893
215361
213939
213777
211620
210020
209076
207546
206668
206110
206046
204228
202433
202273
201609
201175
197872
194809
192349
192182
190645
189853
188367
187557
186753
186140
185731
182563
181390
179247
177484
174624
172015
171200
170815
169656
163739
162877
162381
161267
159881
159250
158809
158795
157739
157673
157326
157274
156624
153528
153178
152567
152342
152102
150324
150211
147181
146561
146263
146199
145780
144949
144672
143903
142824
142549
142323
142047
141999
141823
141109
140402
138632
137159
136923
133798
133154
133097
131394
131346
131115
129256
129245
128496
127318
127304
127015
126568
125089
124930
123671
123615
123076
122908
122301
121463
121137
120444
120030
119364
119136
118796
118782
118533
117483

245714
244976
244131
244000
243817
243682
243551
242134
240425
237592
236777
234825
231387
230658
230065
227200
226798
225021
224330
222186
221202
220046
219783
219320
217963
217842
215014
213128
212047
212042
211675
211466
211405
209850
208575
206381
206211
205978
205845
204846
204817
202977
201557
201411
199762
199541
198504
198015
194360
194091
193544
193086
192420
191176
190019
188034
187393
187368
187168
187010
186572
186217
185044
184525
183888
181717
181373
178592
177654
176137
172367
171815
170641
170019
168679
168612
168342
168082
168041
166627
165564
165479
165181
165114
164279
163299
163181
161677
161420
160216
159681
159140
158230
157664
157569
157093
156361
156147
156094
154000
153126
152238
152173
151339
151204
151126
151062
150601
149804
149570
149464
148394
148378
148221
145799
145189
145123
144474
144228
144146
141638
141063
140022
139399
139239
137983
137147
136748
135535
133861
132058
131348
129178
128630
127946
127337
126641
126254
125970
124742
124392
124236
124049

39076
38719
38306
38013
36161
35929
34770
34267
33960
33809
33748
32447
31998
31646
31645
30422
29881
29774
29022
28770
28655
28477
28445
28023
27878
27388
27159
25467
24566
22885
22556
21636
20026
19168
17139
17054
16488
15226
14801
14575
11910
11888
11621
10704
10455
10090
9052
8273
8058
7105
5661
3644
1525829
1522412
1515822
1506424
1464568
1457208
1439368
1433436
1418837
1400666
1400628
1400605
1400270
1399908
1395413
1395227
1370807
1343350
1341296
1335793
1335639
1285398
1285268
1278562
1275407
1265543
1262223
1262067
1256233
1253682
1253215
1250898
1249004
1232384
1232383
1226103
1226041
1221514
1221513
1203382
1190449
1174188
1173759
1158542
1141585
1131138
1130383
1129931
1097751
1095623
1090241
1085761
1084963
1076092
1053165
1053164
1031486
985370
964811
952485
934123
933018
882925
838153
833594
827778
803732
798881
798084
791481
787747
774132
765860
701059
681653
673842
672271
670104
664735
663977
635600
635415
633965
603190
599345
594321
592776
575690
570013
560660
559710


247077
246594
246436
245848
245039
244716
243854
243390
243090
243063
242783
240734
240563
239019
236557
236490
233573
232118
231560
231512
231292
230477
229169
228624
224186
223933
222469
219828
218876
218542
217255
216845
212954
211818
211447
209317
207485
206634
206319
206009
205562
205482
205022
203577
203400
203016
201484
201212
201161
199824
198118
197622
196995
196530
196091
191931
190927
189572
189421
188891
188362
187142
187041
186550
179355
178986
178780
177651
177155
176106
175805
175425
175424
175054
173842
173424
172073
171472
171312
171027
170469
168564
167712
167211
166713
164808
164415
162387
162180
161861
161756
161248
160769
160444
160023
159798
159754
158756
158666
158429
158185
158149
157852
157521
157144
156727
155846
155789
155325
154637
154021
153467
153137
152938
152120
151845
151509
151162
150713
150697
150288
149772
149195
149167
147985
147825
146986
146932
145965
145775
145657
145320
145272
145030
144834
144749
144101
143911
143678
142025
141290
140495
139385

77037
76687
76351
76342
74906
74147
73124
73078
73041
72209
71256
70447
70170
70026
69643
69103
68967
68965
67570
66945
66746
66570
66310
65732
65398
65249
64493
64239
63216
62259
62138
61988
61516
61501
59871
59426
57994
57731
56326
56040
55891
55478
54824
54560
54535
54290
53821
53537
53493
52906
52620
51465
50919
50541
49931
49610
49580
48778
48563
47428
47392
46254
45598
45358
42308
42207
41832
41663
41188
39574
39452
37874
37332
36611
35206
34846
34090
33212
33165
33070
32007
31930
31310
31135
30829
30115
29955
29138
29100
28129
26194
24647
24483
23929
22114
21858
19704
18917
18421
16532
16476
15299
13969
13885
12905
12275
11563
11347
10361
9897
9609
9043
8219
7903
7086
6979
6727
6218
5995
5983
5701
4921
4478
4261
3388
3232
2888
1314
1486685
1486072
1486071
1452309
1449195
1447547
1432680
1401043
1400893
1400215
1396055
1381240
1377969
1332891
1324375
1317901
1317559
1312100
1284173
1278077
1277211
1277085
1276815
1275791
1275773
1256662
1253626
1249871
1248640
1226681
1224024
120

1091891
1087585
1086790
1079925
1076308
1076307
1067947
1060100
1060099
1059741
1055901
1035789
1028895
1016525
1013661
1003019
994174
993431
986059
983234
976269
969079
966605
965207
954302
949041
936988
932381
932330
927720
915128
914571
910328
877345
876625
858456
851959
842095
819702
802343
792759
775093
770276
763730
760047
756692
750625
730735
729986
719330
709042
702433
701448
700685
693178
686366
680468
671081
659365
653352
649120
643735
626492
618263
615956
614617
613613
601626
593779
589649
586115
583790
581936
578915
578572
578297
577277
577227
576338
576184
575716
568027
562572
561274
560401
553970
551878
551330
544589
541398
538626
537503
534297
532042
530724
529348
529048
528767
528752
521347
520725
519744
518007
504308
496226
495850
495323
490197
487690
487093
486961
486430
484908
477292
474384
474209
468367
465535
465068
457233
456662
452975
445154
439597
434714
424766
420465
419062
418688
418350
416892
416474
416287
416266
416023
409980
405149
404043
399785
399017
3988

153262
152483
152383
151905
151775
151703
151698
151105
150963
150931
150880
150646
150312
150262
148490
147992
147912
147885
147771
147649
146308
146030
145341
144265
144263
144169
144159
144138
142811
142310
141382
140906
140136
139990
139153
139118
138765
138211
138133
137985
137190
137058
136902
136646
136640
136522
136186
135477
135313
134074
133980
133137
131665
130960
130942
130574
129111
128736
128657
128400
128341
128289
127188
126352
126217
125677
125551
124141
124067
123668
123114
122610
122221
122215
122009
121847
121662
121526
121420
121220
120590
120353
120266
118839
118685
117873
116918
116130
116013
114966
114589
114334
113254
113094
112861
112707
112339
111639
111198
110439
110330
110259
109916
109468
109422
109278
106835
105539
105080
104997
104979
101569
101176
100710
100546
100296
100164
99238
98295
97343
97160
96565
96564
94897
94560
94491
94401
94392
94387
94270
94042
91641
91115
90786
90588
88619
88441
87904
87900
86885
85601
85558
85344
84653
84498
84467
84356
8

135431
134943
134534
134440
133041
131972
130914
130415
130265
129874
129120
128491
128456
128374
128373
128299
128143
127985
127812
127782
127267
127076
126898
126364
126119
125582
124424
124132
124027
123750
123294
123128
123081
123066
123043
122212
120693
119271
118741
118538
118262
118067
117604
117437
117080
116439
116393
116242
116216
116006
115881
115533
115392
114791
114518
114458
113882
113743
113130
113129
112827
111925
111105
110700
110659
108719
108703
107360
107306
107297
107109
105899
105691
105091
104966
104856
103937
102693
102357
101996
101614
100736
100735
100687
100644
100100
99638
99504
98350
97127
97076
96419
96193
95891
95068
94640
94372
92907
92763
92614
92613
92506
92118
91776
91718
91427
90990
90159
89557
89054
88882
88187
85115
85099
83804
83432
83027
82885
82801
82774
81916
81795
80896
80313
80264
79852
79378
79048
78606
78469
78283
77101
76616
76554
75676
75381
74721
73947
73632
73221
72355
71623
70506
68637
68546
68456
68238
66991
66830
66295
66233
65851
65

284696
282703
282336
281519
281450
278067
275054
274554
273930
273506
272564
271505
270871
269236
269080
268819
267999
267425
267160
266871
266671
265979
265891
265756
265183
264984
264895
264797
264258
263998
260764
259553
259351
259324
257967
257278
255759
255633
255196
255042
254696
254299
253544
253368
253178
251696
251669
251284
249087
248845
248241
246356
246345
245784
244699
244628
244627
243900
243082
242745
242375
241884
241771
241199
241166
241066
240659
239880
239425
239122
238855
238493
235084
235083
234981
234151
232199
232183
231911
230792
228693
227869
227754
224841
224671
224442
223462
223461
223240
220580
219575
219574
219539
219030
218986
218261
218086
216594
216444
215926
215404
214014
213288
213111
211988
211911
211785
211604
211592
210648
210616
208477
207863
207633
207450
207127
206810
206109
205221
205001
205000
204693
203423
203190
202135
201860
201710
201126
200967
200417
199787
198918
198665
198370
197839
197418
196905
196808
195429
194896
194372
194051
190505

153563
153333
153133
152720
152159
152011
151383
151189
150938
150639
149928
149627
149075
148928
148048
147977
147333
146700
146514
145974
145755
145739
145693
145000
144723
144448
144445
143731
143705
143252
143247
142929
142277
141402
141364
140693
140329
139372
138495
138353
138341
138173
137984
137639
137596
137533
137429
136536
136100
135894
135885
135682
134749
134328
133899
133472
133334
133031
132282
132195
131693
131135
130844
130771
130215
130033
129876
129503
129276
128914
128564
127341
127302
126661
126475
126430
125840
125839
125623
124795
124705
123498
123085
123073
123046
121935
121249
121205
120776
120737
120281
120280
120190
119870
119459
119083
119033
118088
118048
117423
116982
116960
116843
116051
115556
114757
114694
114448
114407
113872
112952
112716
112160
112062
110492
108708
107015
106800
105466
105226
104181
103695
103391
102796
102182
101396
101090
100462
99732
99545
98219
97915
97193
97128
96042
95452
95240
94808
94408
94256
93865
93816
93740
93233
91993
91

34283
33804
33389
33282
33185
32393
31678
30851
30700
30600
29765
29111
28937
28335
28036
27987
27836
27151
27018
26809
26058
25553
25293
24790
23710
23414
23314
22406
20992
20981
20444
20132
19867
19866
19398
19370
17832
17525
16054
15961
15541
15270
14389
13868
13745
13476
10283
9819
8466
8392
7639
7526
6750
5295
4440
4266
3234
888
1538520
1533785
1530974
1530973
1526396
1526395
1515156
1497135
1476811
1476756
1471128
1457068
1449222
1441547
1440000
1425995
1417946
1402245
1402132
1401778
1401558
1401473
1401369
1401191
1401137
1400796
1400624
1400425
1400327
1400237
1399997
1399741
1398256
1397002
1396196
1396117
1395903
1388862
1384859
1384650
1384040
1382769
1380959
1363996
1363995
1359752
1357565
1353393
1348216
1345095
1341470
1335016
1331742
1327169
1324869
1324799
1324654
1318470
1318170
1318169
1314424
1297279
1290319
1289923
1282288
1275684
1275253
1250394
1249072
1249039
1248202
1247265
1245452
1234001
1230896
1226101
1219562
1219489
1211526
1201671
1197242
1182042
1158016


39530
39150
38878
38877
38832
37223
36811
36006
35044
34874
34784
34652
34594
33959
33365
33330
32954
32449
32396
32310
31928
31682
31627
31515
30599
29832
29546
28956
28385
23722
21877
21130
20873
20356
20014
19822
19175
19174
19099
18815
18520
18042
17913
17893
17247
17086
15788
15248
15247
15123
14962
14609
13843
13527
12754
12737
12518
12078
11963
10697
9917
9208
9207
8856
7475
7363
6585
6549
6167
4332
4086
3843
3730
3188
1538851
1527991
1527581
1520955
1520954
1489262
1476723
1458225
1456497
1454719
1448408
1448211
1439913
1429178
1429177
1427566
1420491
1413611
1410892
1410373
1410210
1409654
1404611
1403500
1402711
1401419
1401138
1400923
1400815
1400348
1400345
1399849
1399746
1396221
1388564
1387609
1378448
1371763
1365799
1364259
1363348
1359367
1357639
1356592
1354678
1349558
1349068
1347689
1339117
1331684
1330631
1323314
1317336
1316508
1316507
1303497
1298731
1297861
1297833
1288224
1288125
1283144
1283128
1282098
1279051
1276921
1276085
1272361
1262028
1256071
1253289
12

158516
158392
158072
157791
157497
156977
156597
156460
156280
155747
155457
155093
154694
154625
154462
153472
153395
152513
152412
152208
152196
152087
151566
151494
150925
150877
150858
150647
150644
150618
150231
150222
149641
148228
146750
146071
145436
144895
144814
144668
144572
143864
143832
143483
143418
142995
142846
142326
142016
140694
140375
139902
139739
139535
138983
138914
138856
138255
137800
137496
135643
135412
135290
134882
134294
134278
134036
133803
133659
133549
132878
132716
132715
132369
132252
132191
130804
130222
129667
129335
129271
129203
128893
128599
128368
127984
127035
126335
125596
125545
124376
124325
124093
124086
123776
123741
123103
122936
122450
122380
122354
122040
121977
121779
121736
121700
121649
120488
119943
119491
119181
118822
118663
118325
117594
117502
117288
117226
117217
117177
116939
116806
116800
116633
115832
115503
115385
115242
114886
114677
114591
114457
114440
113347
113025
111897
111860
111432
110809
109233
108862
108480
107110

1019490
1014189
1013732
1003768
1001536
1001535
1001367
998752
994997
990950
990187
988163
987885
977233
974259
968910
959696
959507
952860
939133
935551
934271
932404
930775
930562
927334
927277
927276
926081
925661
922500
921951
915081
914421
912869
910768
910277
907672
904456
896953
894898
889044
888765
886185
885814
883836
883797
867493
866946
866411
851305
843662
835956
833761
828443
822655
821821
818411
817539
817538
810567
809422
808678
806152
798072
798023
792033
788257
784396
775138
774763
774664
770308
769690
767113
765831
765369
764142
761130
757655
753100
750532
745064
741843
737497
736016
735624
733636
727036
723842
722887
722539
720780
718816
717327
711587
711093
708768
706857
702444
700916
697748
695634
690677
687257
686740
685962
685961
683544
682958
678251
675297
675017
666584
665295
661754
660441
656986
656669
656069
655357
655356
653539
651678
651677
651361
650790
650045
649204
646310
641025
639367
637309
636012
635149
633313
629299
628945
628187
627838
626768
625885

601573
601552
600969
600634
599373
599296
599264
599256
597978
597739
597180
596977
595974
595816
595375
595254
594607
594035
593871
593261
593219
592942
592831
591745
591164
590835
590044
589858
589680
589609
589144
589007
588833
588694
587635
587514
587503
587489
587268
587184
587079
587052
586967
586845
586362
585863
585812
585679
584629
584468
584441
583834
583537
582989
582899
582875
582851
582823
582626
582465
581983
581920
581706
581290
581268
581252
581020
580536
580338
580299
580046
579879
579500
579480
579358
578847
578586
578498
578444
577975
577909
577871
577826
577628
577624
577597
577501
577476
577414
576810
576804
576677
576657
576546
576496
575892
575824
575816
575798
575765
575701
575633
575618
575486
575481
573660
572235
571293
571289
570688
570410
570329
570233
569746
566838
566320
565743
565032
563941
562284
561317
560854
560674
560543
559852
557707
557363
556600
556056
555734
555532
554007
553837
553300
551928
551457
551352
550808
549863
545925
541207
540326
539321

357149
356665
355884
355821
355466
355398
355181
355067
355049
354230
354200
351688
351026
349073
348326
347619
347448
347292
346895
345162
345135
344793
344018
343809
343430
341585
340756
340446
340090
339858
337413
337204
335464
335429
335410
335087
335045
334790
334094
333797
333466
333437
333399
333241
333156
332977
330839
329774
328488
327487
326950
326166
325880
325793
324742
324111
324078
323950
322633
322623
322526
322432
321323
320312
319887
318503
317007
316483
314190
313735
312759
312750
312749
311397
310986
310793
310285
310251
309640
309357
308260
306285
305980
304871
304543
303892
303621
302617
302519
301082
300206
298127
297243
296709
296648
296222
295679
294909
294521
294070
293037
292851
292673
290485
290469
289752
286248
285225
284750
284749
284731
283946
283585
283453
282836
282641
282209
281802
281592
280990
280966
280859
280726
280544
280529
280120
280027
277970
277278
275446
275001
274695
274525
274234
273591
273077
272716
272434
271890
271757
271722
271561
271108

40290
40087
39818
39545
38819
36901
36888
36796
36524
35728
35401
35294
35106
35082
33871
33532
31922
31189
31042
29584
29359
28850
27589
27425
26375
25702
25701
25551
25457
24484
23581
22615
22499
21526
20893
20109
18840
18685
17665
17384
16849
16180
15838
15695
13634
13479
13451
13023
11875
11805
11775
10633
10576
8491
7888
7493
7183
7162
6889
6629
5627
5408
4764
4239
3507
2681
2479
2015
1538391
1522392
1514280
1510524
1487846
1486827
1484788
1476989
1471856
1471848
1465684
1465458
1462002
1458497
1457504
1456685
1456657
1456656
1453036
1450286
1447346
1442121
1441413
1441230
1441216
1439021
1437541
1428818
1427796
1425593
1425319
1421297
1411071
1410854
1410189
1403438
1402840
1402681
1401691
1401690
1401475
1401344
1401231
1401213
1401128
1400979
1397112
1397111
1396797
1396095
1395362
1390024
1387836
1378331
1377648
1376795
1376293
1375985
1374106
1374105
1371780
1370573
1370297
1368768
1357805
1357027
1357011
1352071
1347123
1347031
1346950
1343186
1340365
1335743
1334056
1332721

20994
20741
20053
19431
18694
17482
17472
17256
17199
16199
15835
15432
13571
12280
11862
11540
11174
10105
9699
9691
8841
8840
8550
8266
7492
7226
7210
7042
6843
6713
6593
5959
5230
4418
3302
2108
1767
1238
1541812
1538420
1536102
1534445
1531792
1531462
1531461
1526918
1526747
1520668
1516866
1516699
1516100
1507033
1500943
1487057
1486922
1486862
1480306
1480294
1476955
1466816
1466672
1466240
1465787
1458331
1457837
1457498
1450092
1449218
1448390
1441514
1440038
1439032
1432527
1419235
1418344
1416841
1416275
1413259
1412555
1411909
1410948
1410558
1409677
1404294
1403977
1403933
1402912
1402111
1401481
1401459
1401230
1401159
1400934
1400562
1399944
1399943
1397857
1397083
1396153
1396146
1395687
1395530
1395418
1394967
1394919
1394915
1394834
1393887
1390125
1389230
1388714
1381451
1378584
1378476
1377561
1373763
1366796
1360811
1358097
1356994
1356130
1354316
1354045
1352195
1352049
1351303
1350429
1343013
1337212
1336541
1334958
1334796
1334767
1334766
1331576
1328568
1326265


KeyboardInterrupt: 

In [28]:
print(train_id_mapping[31])

1


In [29]:
for i in range(0,40428967):
    for j in range(0,23):
        a = idd[i][j]
        idd[i][j] = train_id_mapping[a]
        
print(idd)

[[     0   7997 160690 ...  22809   9794  24996]
 [     0   7997 160690 ...  22809   9794  24996]
 [     0   7997 160690 ...  22809   9794  24996]
 ...
 [     0    783      4 ...    950     11    319]
 [     0    783      4 ...     23    522     22]
 [     0    783      4 ...    167     40     29]]


In [30]:
np.savetxt("sorted_idx.txt", idd)
np.savetxt("label.txt", label)

In [35]:
from sklearn.model_selection import train_test_split
import pickle
import os


data  = np.insert(idd, 0, values=label, axis=1)
print(data)

[[    0     0  7997 ... 22809  9794 24996]
 [    0     0  7997 ... 22809  9794 24996]
 [    0     0  7997 ... 22809  9794 24996]
 ...
 [    0     0   783 ...   950    11   319]
 [    1     0   783 ...    23   522    22]
 [    0     0   783 ...   167    40    29]]


In [36]:
from sklearn.model_selection import train_test_split
import pickle
import os


def train_val_test_split(data_df, test_ratio=0.1, val_ratio=0.2, seed=12):
    train, test = train_test_split(data_df, test_size=test_ratio, random_state=seed)
    train, val = train_test_split(train, test_size=val_ratio / (1 - test_ratio), random_state=seed)
    return train, val, test

print("Splitting...")
train_data, val_data, test_data = train_val_test_split(data, test_ratio=0.1, val_ratio=0.2, seed=12)

print("Splitting finish")





Splitting...


In [38]:
print(train_data)

[[   0    0  717 ...   91 1994  918]
 [   0    0  496 ...   19  711  125]
 [   0    0  303 ...   73 2079   96]
 ...
 [   0    0  253 ...   23   11   22]
 [   0    0  616 ...   19   40   31]
 [   1    0  430 ...   35   58   22]]


In [41]:
train_x = train_data[:,1:]    
train_y = train_data[:,0]
val_x = val_data[:,1:]    
val_y = val_data[:,0]
test_x = test_data[:,1:]    
test_y = test_data[:,0]

In [44]:
import torch
from torch.utils.data import Dataset

class Avazu_Dataset(Dataset):
    def __init__(self, train_x,train_y):
        self.x = torch.LongTensor(train_x)
        self.y = torch.Tensor(train_y)

    def __getitem__(self, idx):
        return self.x[idx], torch.ones_like(self.x[idx], dtype=torch.float32), self.y[idx]

    def __len__(self):
        return len(self.x)

In [45]:
print(idd.max())
num_features=idd.max()+1

1544488


In [47]:
print("The dataset has been preprocessed.")
result = [Avazu_Dataset(train_x,train_y), Avazu_Dataset(val_x,val_y), Avazu_Dataset(test_x,test_y), num_features]

The dataset has been preprocessed.


In [48]:
with open(f"click.pickle", 'wb') as handle:
    pickle.dump(result, handle,protocol = 4)
    print("File saved.")

File saved.
